export const productsType = {
    LOADING: "LOADING",
    ERROR: "ERROR",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    ADD_PRODUCT_TO_LIST: "ADD_PRODUCT_TO_LIST",
    REMOVE_PRODUCT_TO_LIST: "REMOVE_PRODUCT_TO_LIST",
    CLEAN_PRODUCT_TO_LIST: "CLEAN_PRODUCT_TO_LIST",
    CREATE_PRODUCTS: "CREATE_PRODUCTS",
    UPDATE_PRODUCT: "UPDATE_PRODUCT"
}

export const suppliersType = {
    LOADING: "LOADING",
    ERROR: "ERROR",
    GET_SUPPLIERS: "GET_SUPPLIERS",
    GET_SUPPLIER: "GET_SUPPLIER",
    CREATE_SUPPLIER: "CREATE_SUPPLIER",
    DELETE_SUPPLIER: "DELETE_SUPPLIER",
    UPDATE_SUPPLIER: "UPDATE_SUPPLIER"
}

export const invoicesType = {
    LOADING: "LOADING",
    ERROR: "ERROR",
    GET_INVOICES: "GET_INVOICES",
    GET_INVOICE: "GET_INVOICE",
    CREATE_INVOICE: "CREATE_INVOICE"
}

export const flyersType = {
    LOADING: "LOADING",
    ERROR: "ERROR",
    GET_FLYERS: "GET_FLYERS",
    GET_FLYER: "GET_FLYER",
    CREATE_FLYER: "CREATE_FLYER"
}
